version: '3.7'

services:
  nginx:
    build:
      context: .
    volumes:
      - "./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf"
      - "./src/:/lua/src/"
    environment:
      - REDIS_HOST=192.168.1.108
    ports:
      - "8889:8888"
    extra_hosts:
      - "host.docker.internal:host-gateway"